version: "3.4"

services:

  postgres:
    image: postgres:16.4
    hostname: db
    environment:
      POSTGRES_DB: "kts"
      POSTGRES_USER: "Admin"
      POSTGRES_PASSWORD: "major_password_admin"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U Admin -d kts" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 5G

volumes:
  db-volume: